var dictInObj = {
    'intro':'De toegang tot deze locatie is beperkt tot geautoriseerde gebruikers.<br /> \
Typ uw gebruikersnaam en wachtwoord.',
    'password':'Wachtwoord',
    'username':'Gebruikersnaam',
    'capslockwarning':'<div class="form-login-warning">Caps Lock staat aan</div><br />\
<div>Met de Caps Lock toets aan kan het ertoe leiden dat u uw wachtwoord niet juist invoerd.</div><br /> \
<div>Je moet op Caps Lock drukken om het uit te schakelen voordat je je wachtwoord invoerd.</div>',
    'login':'Inloggen',
    'collapse_all':'Inklappen',
    'expand_all':'Uitklappen',
    'status':'Status',
    'date':'Datum',
    'logout':'Uitloggen',
    'loggedinas':'U bent ingelogd als:',
    'all':'Alle',
    'healthcare':'Zorg',
    'law':'Recht',
    'opstal':'Opstal',
    'householdeffects':'Inboedel',
    'travel':'Reis',
    'car':'Auto',
    'external_transaction_id':'Externe transactienummer',
    //@todo make one translation of these
    'external_policy_id':'Externe polisnummer',
    'externalPolicyId':'Externe polisnummer',
    //@todo make one translation of these
    'external_relation_id':'External relatienummer',
    'externalRelationId':'External relatienummer',
    'type':'Type',
    'state':'Status',
    'manual':'Handmatig',
    'accepted':'Geaccepteerd',
    'denied':'Geweigerd',
    'yes':'Ja',
    'no':'Nee',
    'both':'Beide',
    'notnedasco':'Niet naar Nedasco',
    'processed':'Verwerkt',
    'temporary_coverage_expired':'Rode bolletjes',
    'policy_received':'Polis ontvangen',
    'policy_correct':'Polis correct',
    //@todo make one translation of these
    'lastname':'Achternaam',
    'lastName':'Achternaam',
    'firstname':'Voornaam',
    'middlename':'Tussenvoegsel',
    'city':'Plaats',
    'bankaccount':'Bankrek.',
    'tipafriendid':'Id',
    'view_mutation':'Mutaties',
    'view_tipafriend':'Tip een vriend',
    'referrer':'Referrer',
    'product':'Product',
    'transaction_id':'Transactienummer',
    //@todo make one translation of these
    'relation_id':'Relatienummer',
    'relationId':'Relatienummer',
    'email':'E-mail',
    'testtransaction':'Test transactie',
    'double_transaction':'Dubbele transactie',
    'withdrawed_transaction':'Ingetrokken transactie',
    'requestdate_until':'Aanvraagdatum t/m',
    'requestdate_from':'Aanvraagdatum van',
    //@todo make one translation of these
    'requestDate':'Aanvraag datum',
    'request_date':'Aanvraag datum',
    //@todo make one translation of these
    'start_date':'Start datum',
    'startdate':'Start datum',
    //@todo make one translation of these
    'effective_date':'Ingangsdatum',
    'start_date':'Ingangsdatum',
    'temporary_coverage':'Voorlopige dekking verleend?',
    'name':'Naam',
    'search':'Zoek',
    'search_transactions':'Zoek een transactie',
    'view_transactions':'Transacties',
    'emailaddress':'E-mailAdres',
    'phonedaytime':'Telefoon overdag',
    'phonenighttime':'Telefoon \'s avonds',
    'direct_debit':'Incasso',
    'bank_giro_account':'Bank/girorekening',
    'regular_driver':'Verzekeringsnemer is regelmatige bestuurder',
    'gender':'Geslacht',
    'dayofbirth':'Geboorte datum',
    'adress':'Adres',
    'civil_service':'Ambtenaar',
    'elaborate_on_occupation':'Toelichting beroep',
    'valid_drivers_licence':'Geldig Nederlands rijbewijs',
    'age_driverslicense_aquired':'Leeftijd rijbewijs behaald',
    'date_driverslicense_aquired':'Datum rijbewijs behaald',
    'categories_driverslicense':'categorieën rijbewijs',
    'temporaryTransaction':'Tijdelijke transactie',
    'secondsend':'Tweede verzending',
    'years_insured':'Jaren verzekerd',
    'years_without_damage':'Jaren_shadevrij',
    'years_without_damage_in_compare':'Jaren schadevrij opnemen in de vergelijking',
    'brand':'Merk',
    'model':'Model',
    'build_month_year':'Bouw maand/jaar',
    'fuel':'Brandstof',
    'weight':'Gewicht',
    'power':'Vermogen',
    'turbo':'Turbo',
    'engine_displacement':'Cilinderinhoud',
    'newvalue':'Nieuwwaarde',
    'dayvalue':'dagwaarde',
    'value_audio':'Waarde audio',
    'value_accessoire':'Waarde accessoires',
    'elaboration_security':'Toelichting beveiliging',
    'gear':'Versnelling',
    'securityclass':'Beveiligingsklasse',
    'security_tno_scm_validated':'Beveiliging TNO/SCM gekeurd',
    'elaboration_accessoire':'Toelichting accessoires',
    'counter_mileage':'Tellerstand',
    'gray_numberplate':'Grijs kenteken',
    'reporting_code':'Meldcode',
    'usage':'Gebruik',
    'elaboration_usage':'Toelichting gebruik',
    'foreign_usage':'Buitenlands gebruik',
    'lease_finance_rent':'Lease, financiering of (ver-)huur',
    'previous_insurer':'Vorig verzekeraar',
    'product_name':'Productnaam',
    'product_id':'Product ID',
    'coverage_form':'Dekkingsvorm',
    'additions':'Toevoegingen',
    'premium':'Premie',
    'own_risk':'Eigen risico',
    'policy_costs':'Poliskosten',
    'bonus_malus_discount':'Bonus/malus korting',
    'payment_term':'Betalingstermijn',
    'mileage':'Kilometrage',
    'additional_coverage_accessory':'Aanvullend met accessoiredekking',
    'additional_occupants':'Aanvullend met ongeval inzittenden',
    'additional_with_legal':'Aanvullend met rechtsbijstand',
    'additional_damage_to_occupants':'Aanvullend met schade inzittenden',
    'bonus_malus_declaration':'Bonus/malus-verklaring',
    'endorsements_licence':'Staan er aantekeningen op het rijbewijs',
    'criminal_record':'Is er de afgelopen 8 jaar spraken geweest van een strafrechtelijk verleden of is de rijbevoegdheid ontzegd geweest',
    'influence_driving_ability':'Is er sprake van be\u00efnvloeding van de rijvaardigheid?',
    'relevant_items':'Heeft u nog iets mede te delen zowel ten aanzien van het te verzekeren risico aldsde aanvrager/belanghebbende(n) dat voor het beoordelen van de aanvraag van belang zou  kunnen zijn?',
    'damages':'Aantal schades',
    'canceled_insurance_last_8_year':'Is er de laatste 8 jaar een verzekering van welk aard dan ook opgezegd of aangeboden op beperkte en/of verzwarende omstandigheden',
    'xml_request':'XML Request',
    'xml_response':'XML Response',
    'xml_verify':'XML XML verifi\u00eber',
    'xml_verified':'XML geverifi\u00eberd',
    'rolls_xml_request':'Rolls XML request',
    'rolls_xml_response':'Rolls XML response',
    'change':'Wijziging',
    'insurance':'Verzekering',
    'request':'Aanvraag',
    'sender_confirmationmail':'Afzender bevestigingsmail',
    'policy_id':'Polisnummer',
    'state_history':'Status history',
    'last_change':'Laatst gewijzigd',
    'transaction_detail_temporary_coverage':'Tijdelijke dekking',
    'transaction_detail_policy_correct':'Zo ja was alles correct',
    'catalog_value':'Catalogus waarde',
    'objecttype':'Object soort',
    'licenceplate_valid':'Kenteken/meldcode geldig',
    'user_id':'Gebruikersnummer',
    'relation_nedasco_id':'Relatienummer Nedasco',
    'show_user_%s':'Bekijk gebruiker %s',
    'show_relation':'Bekijk relatie %s',
    'add_note':'Notitie toevoegen',
    'show_transactions':'Transacties',
    'Notes':'Notities',
    'noteId':'Notitie nummer',
    'practitioner':'Behandelaar',
    'dateCreated':'Aangemaakt',
    'dateDeadline':'Deadline',
    'dateClosed':'Gesloten',
    'priority':'Prioriteit',
    'mutation':'Mutatie',
    'show_relation_%s':'Toon relatie %s',
    'mutationreason':'Reden mutatie',
    'reason1':'Reden 1',
    'relation_detail':'Relatie detail',
    //@todo make one translation of these
    'updatedAt':'Gewijzigd op',
    'changeDate':'Gewijzigd op',
    'changeReason':'Reden wijziging',
    'referer':'referer',
    'offer':'Offerte',
    'title':'Titel',
    'template_type':'Template soort',
    'incoming':'Inkomend',
    'transactionId':'Transactienummer',
    'mutationStatus':'Mutatie status',
    'dekking':'dekking',
    'changeNote':'Notitie verandering',
    'correspondence_detail':'Correspondentie detail',
    'outgoing':'Uitgaand',
    'intern':'intern',
    'subject':'Onderwerp',
    'from':'Van',
    'name_customer':'Naam klant',
    'name_user':'Naam gebruiker',
    'firstname_user':'Voornaam gebruiker',
    'other':'Anders',
    'to':'Naar',
    'emailfrom':'Email van',
    'email_customer':'Email klant',
    'salutation':'Aanhef',
    'correspondence':'Correspondentie',
    'add_correspondence':'Correspondentie toevoegen',
    'emailto':'Email naar',
    'must_be_a_numeric_ip_address':'Moet een nummeriek ip addres zijn',
    'passwords_do_not_match':'Wachtwoorden komen niet overeen',
    'passwords_needs_to_contain_as_well_numbers_as_characters_and_needs_to_be_at_least':'Wachtwoorden moeten cijfers en letter bevatten en tenminste',
    'add':'Nieuw',
    'delete':'Verwijder',
    'export':'Exporteren',
    'save':'Opslaan',
    'cancel':'Cancel',
    'enddate':'Eind datum',
    'total':'Totaal',
    'period1':'Periode 1',
    'period2':'Periode 2',
    'health_statistics':'Zorg statistieken vergelijken',
    'search_now':'Zoek',
    'view_relations':'Relaties',
    'customer_service':'Klanten service',
    'search_customer':'Zoek klant',
    'view_customers':'Klanten',
    'edit_user':'Bewerk gebruiker',
    'driversLicenceSince':'Rijbewijs sinds',
    'licencePlateId':'Kenteken',
    'initials':'Initialen',
    'male':'Man',
    'female':'Vrouw',
    'family_composition':'Gezins samenstelling',
    'houseNr':'huisNr',
    'number':'huisNr',
    'houseNrSuffix':'toevoeging',
    'number_suffix':'toevoeging',
    'postal_code':'Postcode',
    'telephone':'Telefoon',
    'insurer_detail':'Verzekeraar detail',
    'giroAccount':'Gironummer',
    'bankAccount':'Banknummer',
    'birthdate':'Geboortedatum',
    'relationId_grid':'Relatienummer (vs)',
    'type_address':'Adres type',
    'street':"Straat",
    'zipCode':'Postcode',
    'edit_note':'Bewerk notitie',
    'change_note':'Opslaan',
    'view_healthembargo':'Zorg embargo',
    'embargo_date':'Embargo datum',
    'view_categories':'Categori\u00ebn',
    'email_categories':'Email categori\u00ebn',
    'save_category_create_%s':'Categorie met de naam %s is succesvol toegevoegd',
    'save_category_update_%s':'Categorie met de naam %s is succesvol aangepast',
    'fail_category_create':'Toevoegen van de categorie is mislukt',
    'fail_category_update':'Updaten van de categorie is mislukt',
    'with_error':'Met de fout',
    'kind':'Soort',
    'is_active':"Is actief",
    'is_double':'Is dubbel',
    'max_duration':'Maximale duratie tijdelijke dekking',
    'ref':'Ref',
    'insurer':'Verzekeraar',
    'is_test':'Is test',
    'regularDriver':'Regelmatige bestuurder',
    'paymentTermInMonths':'Betalings termijn in mnd.',
    'transactionType':'Soort transactie',
    'temporary_coverage_columm':'Tijdelijke dekking',
    'callback_explain':'Selecteer een begindatum en tijd, en een einddatum en tijd',
    'fail_signature_save':'Opslaan van de handtekening is mislukt',
    'save_signature_saveed':'Handtekening is opgeslagen',
    'signature':'Handtekening',
    'signature_explain':'Hier kunnen live de handtekeningen van de automatisch gestuurde mails worden aangepast.',
    'email_detail':'Emails',
    'emailsignature_detail':'Edit E-mail handtekening',
    'remark':'Opmerking',
    'id_vs_id':'id/vs id',
    'view_rollsproducts':'Rolls producten',
    'opinion':'Klantopinie',
    'rollsLinkId':'koppel RollsID',
    'was_saved':'is opgeslagen',
    'createCallBack':'Callback CSV lijst aanmaken',
    'insurrerwinrolls':'Insurer winrolls',
    'view_rollsinsurers':'Verzekeraars/winrolls',
    'view_NedascoRolls':'Nedasco/rolls',
    'id':'id',
    'insurerId':'Verzekeraar id',
    'insurerName':'Verzekeraar',
    'rollsProductd':'prodNrRolls',
    'rollsProductName':'Rolls product naam',
    'catId':'Categorie',
    'change_end_text':'Eind text',
    'change_offermail':'Offerte mail',
    'createCallback':'Callback CSV lijst aanmaken',
    'view_customer':'Klanten overzicht',
    'time':'Tijd',
    'filter':'filter',
    'postcode':'Postcode',
    'birthDate':'Geboortedatum',
    'reset':'Reset',
    'occupation':'occupation',
    'bsn':'bsn',
    'addressess':'Addressen',
    'tav':'tav',
    'polis_overview':'Polis overzicht',
    'Ned':'Ned',
    'description':'Omschijving',
    'coverage':'Dekking',
    'coverageA':'Dekking A',
    'coverageB':'Dekking B',
    'coverageD':'Dekking D',
    'startDate':'Startdatum',
    'contractState':'Contract status',
    'mutation_forms':'Mutatie formulieren',
    'createdAt':'Aangemaakt op',
    'phoneDayTime':'Telefoonnummer overdag',
    'phoneNightTime':'Telefoonnummer s\'avonds',
    'userName':'Gebruikersnaam',
    'passwordRepeat':'Herhaal',
    'blocked':'Geblokeerd',
    'faultyLogins':'Foutief ingelogs',
    'password_explain':'Wachtwoord moet tenminste 6 karaters lang zijn en zowel nummers als letters bevatten.',
    'not_found':'Niet gevonden',
    'showClosed':'Toon gesloten',
    'deadlineFrom':'Deadline van',
    'deadlineUntil':'Deadline t/m',
    'lastUpdateBy':'geupdate door',
    'unknown':'onbekend',
    'low':'Laag',
    'normal':'Normaal',
    'high':'Hoog',
    'urgent':'Urgent',
    'active':'Actief',
    'Default text':'Default text',
    'Notitie toevoegen':'Notitie toevoegen',
    'Transacties':'Transacties',
    'correspondence_id':'Correspondentie id',
    'bcc':'bcc',
    'internal_correspondence':'Interne correspondentie',
    'internalCorrespondence':'Interne correspondentie',
    'messages':'berichten',
    'correspondenceType':'Correspondentie type',
    'phone':'telefoon',
    'oral':'mondeling',
    'fax':'fax',
    'sms':'sms',
    'post':'post',
    'none':'geen',
    'correspondenceTemplate':'Correspondentie template',
    'typeRelation':'type',
    'all_relations':'Alle relaties',
    'just_users':'Alleen gebruikers',
    'no_users':'Geen gebruikers',
    'remove_doubles':'Filter dubbelen',
    'postalcode':'Postcode',
    'policyId':'Polisnummer',
    'userId':'Gebruikers id',
    'dateUpdated':'Laatst geupdate',
    'columns':'Kollomen',
    'temporary_coverage_column':'Tijdelijke dekking',
    'ref2':'ref2',
    'transaction_type':'Transactie type',
    'counted_fields':'Getelde velden',
    'html_data':'HTML data',
    'html':'HTML',
    'Reset':'Reset',
    'leadoverview':'Leads overzicht',
    'insurencetype':'Type',
    'zorg':'zorg',
    'referer2':'referer2',
    'health':'Zorg',
    'legal':'legal',
    'home':'home',
    'contents':'Inhoud',
    'view_correspondences':'Correspondentie',
    'view_emails':'Email templates',
    'subject_emailtemplate':'Email template',
    'emailcategory':'Email categorie',
    'blacklist':'blacklist',
    'attachements':'attachements',
    'text':'text',
    'files':'files',
    'upload':'Upload',
    'Upload':'Upload',
    'value':'waarde',
    'rollsProductId':'rolls ProductNummer',
    'url':'Url',
    'nedascorolls':'Nedasco/rolls',
    'view_rollsnedasco':'Nedasco/rolls overzicht',
    'productCategoryId':'Product categorie',
    'nedInsId':'nedInsId',
    'noClaimP':'noClaimP',
    'monthsCat':'Maanden Categorie',
    'rollsId':'Rolls Id',
    'nedascoId':'Nedasco Id',
    'view_AutoAddon':'Product auto addon',
    'productId':'Product',
    'comboId':'Combination',
    'yearPremium4':'J.premie 4',
    'monthPremium4':'M.premie 4',
    'yearPremium5':'J.premie 5',
    'monthPremium5':'M.premie 5',
    'yearPremium6':'J.premie 6',
    'monthPremium6':'M.premie 6',
    'yearPremium7':'J.premie 7',
    'monthPremium7':'M.premie 7',
    'yearPremium8':'J.premie 8',
    'monthPremium8':'M.premie 8',
    'autoaddon':'Product autoaddon',
    'productLabel':'Product label',
    'label':'Product label',
    'productName':'Product naam',
    'missedleads':'Gemiste leads',
    'not_active':'Niet actief',
    'categoryId':'Categorie',
    'view_mailtype':'Mailtypes',
    'saving_data':'Aan het opslaan',
    'creating_file':'Export bestand aan het maken',
    'downloading_failed':'Aanmaken mislukt, probeer het nogmaals',
    'download_link':'Download bestand',
    'healthnumbers':'Zorg aantallen',
    'amount':'Aantal',
    'percentage':'Percentage',
    'fullname':'Naam',
    'productType':'Producttype',
    'productTypeState':'Producttype status',
    'por':'POR',
    'por_code':'POR',
    'edit':'Bewerk',
    'view_Insurer':'Verzekeraars',
    'Insurer_filter':'Zoek',
    'zorgWebId':'ZorgWeb id',
    'moneyViewName':'MoneyView naam',
    'agentId':'Agent id',
    'generalUrl':'Algemene url',
    'note':'Notitie',
    'producttypes':'Product Type',
    'addresses':'Adressen',
    'general':"Algemeen",
    'logo':'Logo',
    'openingTimes':'Openings tijden',
    'information':'Informatie',
    'upload_logo':'Upload een logo',
    'change_address':'Bewerk adress',
    'publish_online':'Informatie publiceren op de website',
    'confirm_delete':'Bevestig verwijderen',
    'do_you_want_to_remove_this_record':"Weet u zeker dat u dit record wilt verwijderen?",
    'compareText':'Vergelijk tekst',
    'no_products':'Geen producten',
    'products_no_partner':'Wel producten - Geen samenwerking (producten zijn dan wel in de vergelijking opgenomen)',
    'products_clicks':'Wel producten - Clicks',
    'products_offers':'Wel producten - Offertes',
    'products_closed_insurances_vs':'Wel producten - Gesloten verzekeringen (op site van Verzekeringssite.nl)',
    'products_closed_insurances_insurer':'Wel producten - Gesloten verzekeringen (op site van verzekeraar)',
    'products_closed_insurances_affiliate':'Wel producten - Gesloten verzekeringen (affiliate kanaal)',
    'question':'Vraag',
    'show':'Tonen',
    'always':'Altijd',
    'medicalandteeth':'Medische- en tandselectie',
    'medical':'Medische selectie',
    'teeth':'Tandselectie',
    'elaboration':'Toelichting',
    'elaborationFor':'Toelichting voor',
    'extra':'Extra slotvraag',
    'healthquestion':'Zorg vraag',
    'offerMail':'Offerte Email',
    'requestMail':'Aanvraag Email',
    'change_end_question':'Bewerk eindvraag',
    'producttype_detail':'Product type',
    'products':' Producten',
    'csvMail':'CSV Email',
    'closureUrl':'Afsluit url',
    'directWriter':'Direct writer',
    'addressId':'Adres',
    'customer_opinion':'Klanten opiniecijfer',
    'postPrefil':'Posten / Prefillen',
    'extraQuestions':'Extra sluitvragen',
    'product_details':'Product',
    'add_insurer':'Voeg verzekeraar toe',
    'content':'Content',
    'payment_text':'Betalings tekst',
    'warning_text':'Waarschuwings text',
    'end_declaration':'Slotverklaring',
    'thank_you_text':'Bedankt tekst',
    'thank_you_text_medical':'Bedankt tekst medisch',
    'end_texts_and_mails':'Sluit mail & teksten',
    'productState':'Product Status',
    'plus_points':'Pluspunten',
    'min_points':'Minpunten',
    'free':'Gratis',
    'paid':'Betaald',
    'Offer_filter':'Zoek offerte',
    'offerId':'Offertenummer',
    'From':' van',
    'Until':' tot',
    'productTypeId':'Product type',
    'fullName':'Volledige naam',
    'offers':'Offertes',
    'offersview':'Offertes',
    'view_Offer':'Offertes',
    'process':'verwerken',
    'not_to_nedasco':'Niet naar Nedasco',
    'requestDate_from':'Aanvraag datum van',
    'requestDate_until':'Aanvraag datum tot',
    'clicks':'Clicks',
    'datefrom':'Datum van',
    'dateuntil':'Datum tot',
    'please_wait':'Even geduld A.U.B',
    'missedoffers':'Gemiste offertes',
    'offerstotal':'Offertes aantal',
    'was_succesfully_uploaded':' was succesvol geupload',
    'uploading_your_icon':'Icoon aan het uploaden',
    'fail':'Er is iets mis gegaan tijdens het opslaan',
    'error':'Fout',
    'shownumbers':'Toon aantallen',
    'batchmail_explain':'Via dit menu onderdeel kunt u wanbetalers een email versturen. In de eerste stap kunt u de gegevens invoeren m.b.t. de wanbetalers. \
     Per regel moet u ingeven: "branchecode polisnummer bedrag". De waarden moeten gescheiden zijn door een tabteken.',
    'input':'Invoer',
    'relation_add':'Nieuwe relatie toevoegen',
    'prefix':'voorvoegsel',
    'pBankAccount':'Postbanknummer',
    'of':'van',
    'EmailTemplates_edit_change':'E-mail templates edit/add',
    'emailbody':'body',
    'view_EmailTemplates':'E-mail templates overzicht',
    'new':'Nieuw',
    'pending':"In behandeling",
    'process_completed':"Verwerken/Afgerond",
    'waiting_for_customer':"Wachten op klant",
    'waiting_for_nedasco':"Wachten op Nedasco",
    'waiting_for_third':"Wachten op derde",
    'Customers_filter':'Zoeken Klant',
    'view_Customers':"Klanten",
    'practitionerId':"Behandelaar",
    'Mutations_filter':'Zoek mutaties',
    'view_Mutations':"Mutaties",
    'attempts':"Pogingen",
    'Relation_filter':"Zoeken relaties",
    'view_Relation':"Relaties",
    'admin':"Admin",
    'editor':"Editor",
    'cms':"Cms",
    'affiliate':'Affiliate',
    'guest':"Guest",
    'Notes_filter':"Zoek notitie",
    'view_Notes':"Notities",
    'dateDeadline_from':'Deadline van',
    'dateDeadline_until':"Deadline t/m",
    'linkId':"Rollslink id",
    'wizard':"Wizard",
    'credited':"Gecrediteerd",
    'dateFrom':"Datum van",
    'dateUntil':"Date t/m",
    'offerData':"Offerte gegevens",
    'credit':"Crediteer",
    'debet':"Debiteer",
    'OfferTotals_filter':"Offerte aantallen zoeken",
    'view_OfferTotals':"Offerte aantallen",
    'pos':"Pos",
    'Missed_filter':"Gemisde offertes zoeken",
    'view_Missed':"Gemisde offertes",
    'offer_id':"Offerte id",
    'productTypeName':"Type",
    'createdAt_from':"Aangemaakt op van",
    'createdAt_until':" Aangemaakt op t/m",
    'detail':'Detail'
};